common: &common
  adapter: postgresql
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000

production:
  <<: *common
  database: ripul_pro

development:
  <<: *common
  database: ripul_dev

test:
  <<: *common
  database: ripul_test
